name: CD - Deploy via Docker

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy container
        uses: appleboy/ssh-action@v1
        with:
          host: course.prafdin.ru
          username: belyakova
          port: 2458
          script: |
            echo "🔁 Pull new Docker image..."
            docker stop catty-container || true
            docker rm catty-container || true
            docker pull ghcr.io/${{ github.repository_owner }}/catty-app:latest
            docker run -d -p 8181:80 --name catty-container ghcr.io/${{ github.repository_owner }}/catty-app:latest
            echo "✅ Deployed new version!"
