name: CD - Deploy application to server

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy files to server
        uses: appleboy/scp-action@v1
        with:
          host: course.prafdin.ru
          username: ulyana
          port: 2458
          source: "."
          target: "/home/ulyana/devops/app"

      - name: Deploy & restart
        uses: appleboy/ssh-action@v1
        with:
          host: course.prafdin.ru
          username: ulyana
          port: 2458
          script: |
            cd /home/ulyana/devops/app || exit 1
            chmod +x test.sh
            ./test.sh || exit 1
            sudo systemctl restart catty.service
